### ISSUE TITLE
Per project ender configs

### ISSUE THREAD

**Issue by ideamonk** [prajwalit/ender#1]
It would be nice if ender picked up the `.ender` file from current dir if available instead of just home.
In that way each project could have it's own ender config.

**Comment by prajwalit** [comment]
Hey,

I didn't do it that way because of following reasons -
1) This way you can open any project from any directory.
2) Sometimes you need different combinations for same project. For eg, I have a project which I open one way if I'm running locally and some other way if I'm connecting to office machine.
3) Adding `default: true` attribute in the most frequently used project makes it easier to open the project.

Makes sense?
